.DEFAULT_GOAL: models

prepare:
	@echo "Preparing corpus.txt"
	sh -c "/usr/local/bin/prepare --es-url=http://$(ELASTIC_HOST):9200/content corpus.txt"

label:
	@echo "Labeling corpus.txt"
	sh -c "/usr/local/bin/label corpus.txt labeled-corpus --kg-url=http://$(API_HOST)/api/knowledge-graph/dump_all/"

train_kv:
	@echo "Training word embeddings"
	sh -c "/usr/local/bin/kv corpus.txt corpus-ft"

train_keras:
	@echo "Training keras model"
	sh -c "/usr/local/bin/train --cpu k-model.hdf corpus-ft corpus.txt --kg-url=http://$(API_HOST)/api/knowledge-graph/dump_all/"

train_ft:
	@echo "Training fasttext model"
	sh -c "/app/fastText/fasttext supervised -input labeled-corpus-train -output labeled-corpus -lr 0.5 -epoch 40 -wordNgrams 2 -bucket 2000000 -dim 50"

models:prepare label train_kv train_keras train_ft
